### ISSUE TITLE
A small question on the code

### ISSUE THREAD

**Issue by jakeoung** [oterobaguer/dip-ct-benchmark#2]
Thanks for this great code which helps me a lot. While I look into the following code:

https://github.com/oterobaguer/dip-ct-benchmark/blob/0539c284c94089ed86421ea0892cd68aa1d0575a/dliplib/utils/models/iterative.py#L112

I wonder if why it slices `1:2` in `primal_evalop = self.op(primal_cur[:, 1:2, ...])`, instead of `0:1` as done in dual_evalop.

Thanks in advance!

**Comment by oterobaguer** [comment]
Hi!
sorry for not answering before :(

In the learned primal-dual scheme, the input to the forward operator is
chosen freely by the network, see the original paper
<https://ieeexplore.ieee.org/document/8271999> (arxiv
<https://arxiv.org/pdf/1707.06474.pdf>) in Section III. C in the third
bullet point. This is realized via the second output channel of the network
Lambda. While in Algorithm 2 in the paper the input is denoted f-bar_i, in
Algorithm 3 it becomes f^(2)_(i-1). It is actually one of the "memory"
channels (introduced in the first bullet point in Section III. C), which is
chosen to have the special role of defining the input to the forward
operator.

In our code, the network Lambda is implemented by the lines:
primal_update = self.primal_blocks[i](primal_update)
primal_cur = primal_cur + primal_update
The second channel of this tensor corresponds to f^(2)_(i-1) in the next
iteration.


Kind regards,
Daniel

**Comment by jakeoung** [comment]
Thank you very much for the detailed comment, which helps me a lot! And sorry for taking your time; I realise that I need to be careful in details.

Kind regards,
Jakeoung
